queue_rules:
  - name: default
    merge_conditions:
      - check-success=slow-ci
    queue_conditions:
      - label=ready-to-merge

pull_request_rules:
  - name: queue on label
    conditions:
      - label=ready-to-merge
    actions:
      queue:
        name: default
